use super::*;

#[test]
fn xref_stream_resolves_flate_object_stream_and_checks_index_identity() {
    let mut pdf = PdfFixture::new();
    let parent = pdf.object(
        8,
        0,
        "<< /Type /ObjStm /N 2 /First 9 /Length 17 >>\nstream\n1 0 2 3  42 (yes)\nendstream",
    );
    // Replace the body with a Flate stream generated by Python's independent zlib implementation.
    pdf.data.truncate(parent);
    let compressed: &[u8] = &[
        120, 156, 51, 84, 48, 80, 48, 82, 48, 86, 80, 48, 49, 82, 208, 168, 76, 45, 214, 4, 0, 27,
        37, 3, 143,
    ];
    pdf.data.extend_from_slice(
        format!(
            "8 0 obj\n<< /Type /ObjStm /N 2 /First 9 /Filter /FlateDecode /Length {} >>\nstream\n",
            compressed.len()
        )
        .as_bytes(),
    );
    pdf.data.extend_from_slice(compressed);
    pdf.data.extend_from_slice(b"\nendstream\nendobj\n");
    let start = pdf.data.len();
    let rows: &[(u8, u16, u8)] = &[
        (2, 8, 0),
        (2, 8, 1),
        (2, 8, 0),
        (2, 8, 9),
        (1, u16::try_from(parent).unwrap(), 0),
    ];
    pdf.data.extend_from_slice(b"9 0 obj\n<< /Type /XRef /Size 10 /Root 1 0 R /W [1 2 1] /Index [1 4 8 1] /Length 20 >>\nstream\n");
    for (kind, field, last) in rows {
        pdf.data.push(*kind);
        pdf.data.extend(field.to_be_bytes());
        pdf.data.push(*last);
    }
    pdf.data
        .extend_from_slice(format!("\nendstream\nendobj\nstartxref\n{start}\n%%EOF\n").as_bytes());
    let mut resolver = ObjectResolver::open(&pdf.data).unwrap();
    assert_eq!(
        *resolver.resolve(reference(1, 0)).unwrap(),
        PdfObject::from(42)
    );
    assert!(matches!(
        resolver.resolve(reference(2, 0)).unwrap().as_ref(),
        PdfObject::String(_)
    ));
    assert!(matches!(
        resolver.resolve(reference(1, 1)),
        Err(ResolveError::GenerationMismatch { .. })
    ));
    assert!(matches!(
        resolver.resolve(reference(3, 0)),
        Err(ResolveError::ObjectMismatch { .. })
    ));
    assert!(matches!(
        resolver.resolve(reference(4, 0)),
        Err(ResolveError::ObjectStream(_))
    ));
}

#[test]
fn parent_must_be_an_uncompressed_stream_with_matching_header() {
    let input = b"%PDF-1.7\n8 0 obj 42 endobj";
    let header = PdfHeader::parse(input).unwrap();
    for parent in [
        None,
        Some(XRefEntry::InObjectStream {
            stream_object: ObjectNumber::new(8).unwrap(),
            index_in_stream: 0,
        }),
        Some(XRefEntry::InUse {
            offset: ByteOffset::new(9),
            generation: GenerationNumber::new(0),
        }),
    ] {
        let mut table = XRefTable::new();
        table.insert(
            ObjectNumber::new(1).unwrap(),
            XRefEntry::InObjectStream {
                stream_object: ObjectNumber::new(8).unwrap(),
                index_in_stream: 0,
            },
        );
        if let Some(entry) = parent {
            table.insert(ObjectNumber::new(8).unwrap(), entry);
        }
        let mut resolver = ObjectResolver::new(input, header, table);
        assert!(matches!(
            resolver.resolve(reference(1, 0)),
            Err(ResolveError::InvalidObjectStream(_))
        ));
    }
}
